### ISSUE TITLE
flutter packages get 时报错

### ISSUE THREAD

**Issue by lavender1026** [jaggerwang/flutter-in-practice#1]
报  ! analyzer 0.39.6
环境变量也有配置。。不知道咋回事，跑不了demo

**Comment by jaggerwang** [comment]
请提供详细错误日志和运行环境。

**Comment by LiuCao** [comment]
有可能是包冲突，版本兼容问题，可尝试在`pubspec.yaml`文件中的`dependency_overrides`下添加最新版的 `build_resolvers` 来解决。例如：
```
dependency_overrides:
  build_resolvers: ^1.3.4
  analyzer: ^0.39.6
```

**Comment by jaggerwang** [comment]
如 @LiuCao 所说，有些时候某几个包依赖同一个包，但要求的版本有冲突，就只能通过 `dependency_overrides`  来解决。比如现在的代码里 `functional_data_generator` 包很久没有更新，要求的 `analyzer` 包版本比较老 `>=0.34.0 <0.37.0`，而其它包要求的 `analyzer` 包版本又比较新，所以只能通过 `dependency_overrides` 强制指定 `analyzer` 包的版本号。

```yaml
dependency_overrides:
  analyzer: ^0.39.4
```

大多数的时候高版本会兼容低版本接口，但也有不兼容的时候，这个时候只能从冲突包列表里舍弃其中一种了。

**Comment by lavender1026** [comment]
万分感谢，回去看看可以用不
