### ISSUE TITLE
如何解决不同分辨率字体大小和尺寸大小同比缩放问题

### ISSUE THREAD

**Issue by LiuCao** [jaggerwang/flutter-in-practice#2]
拉了下代码研读了一遍，觉得结构还是比较清晰的，而且也解决了很多开发中的问题，赞。
就是有一个问题，在不同分辨率的手机上，尺寸和字体大小要怎么解决。iPhone 6上的尺寸都正常，在iPhone SE上就显得乱了。有没有什么优雅的结局方案？

**Comment by jaggerwang** [comment]
可以试一下这个库，https://pub.dev/packages/flutter_screenutil
